blank_issues_enabled: true
contact_links:
  - name: "\U0001F468‍\U0001F4BB General Community Support"
    url: https://discord.pivx.org
    about: Please ask general support questions in our discord server.
